### ISSUE TITLE
Open to new feature PR?

### ISSUE THREAD

**Issue by brainlid** [Nebo15/confex#10]
Are you guys open to a PR for giving a helpful error with the name of the required ENV value?

Example:

```elixir
config :core, :test_required_int, {:system, :integer, "TEST_REQUIRED_INT"}
```

Now, when the ENV variable is NOT SET, in a console:

```elixir
> Confex.get(:core, :test_required_int)
** (MatchError) no match of right hand side value: :error
    (confex) lib/confex.ex:147: Confex.cast/2
    (confex) lib/confex.ex:112: Confex.get_value/1
    (confex) lib/confex.ex:36: Confex.get/3
```

I would like to update the library to treat that as required and give a helpful error message like "ENV setting 'TEST_REQUIRED_INT' is required".

Then if the value exists but can't be parsed to an integer, I get the same error message as above. I would prefer to get an error like "ENV setting 'TEST_REQUIRED_INT' value error: \"abc\" failed to convert to an integer".

Are you guys open to receiving this type of a feature? 

When we have front-end developers running a local backend, if they are missing or have badly configured environment settings, using both `System.get_env` and the current way `Confex` works give no help in figuring out which, of the many settings available, has a problem.

**Comment by AndrewDryga** [comment]
Hello. Sure, we open for any kind of contributions. 

I like the idea to tell what exactly was wrong, submit a PR 👍 .

**Comment by AndrewDryga** [comment]
Version 2.0.0 now raises when integer or boolean can not be parsed.
