### ISSUE TITLE
Possible to use with Ecto?

### ISSUE THREAD

**Issue by dropfen** [Nebo15/confex#11]
When I am building a release, how can I use confex to define the DB credentials from within the environment? I mean the environment, from where I am running the release not building.

Well, this would be the nice to have case :)

```
config :app, App.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: {:system, "PG_USER"},
  password: {:system, "PG_PASS"},
  hostname: {:system, "PG_HOST"},
  database: {:system, "PG_DB"},
  pool_size: 15
```

Thanks!

**Comment by AndrewDryga** [comment]
Hi.

Ecto has `init` callback, we use it in all our projects with Confex:
```
defmodule MyApp do
  use Ecto.Repo, otp_app: :my_app

  @doc """
  Dynamically loads the repository configuration from the environment variables.
  """
  def init(_, config) do
    url = System.get_env("DATABASE_URL")
    config = if url, do: Ecto.Repo.Supervisor.parse_url(url), else: Confex.process_env(config)

    unless config[:database] do
      raise "Set DB_NAME environment variable!"
    end

    unless config[:username] do
      raise "Set DB_USER environment variable!"
    end

    unless config[:password] do
      raise "Set DB_PASSWORD environment variable!"
    end

    unless config[:hostname] do
      raise "Set DB_HOST environment variable!"
    end

    unless config[:port] do
      raise "Set DB_PORT environment variable!"
    end

    {:ok, config}
  end
end
```

**Comment by AndrewDryga** [comment]
@dropfen I've added this sample to README.md, thanks using Confex 👍

**Comment by dropfen** [comment]
@AndrewDryga I just saw it, will try it out ASAP. I guess, I just had the aha moment, for how it works and so on. Let me express: 

- The config.exs is compiled at build time, so there is no way to pass values at runtime
- So, we use callbacks/config-handlers where we are checking the compiled-in configs, and load them if they are missing from **Confex** (its **System.get_env** under the hood)

Still missing point:
- how to handle other libs, where we do not have callbacks? Like guardian for example, or whatever xyz-lib

Thank you Andrew!

Boris

**Comment by dropfen** [comment]
Thanks Andrew, it worked! 👍

**Comment by AndrewDryga** [comment]
Unfortunately It's a question that should be pointed to libraries developers. Usually you have one of few options:
1. You can define default config in `confix.ex`, and pass overrides in supervisor args (when adding external supervisor to your app's supervision tree).
2. Lib can provide callbacks
3. Some libs have their own {:system, ..} tuples implementation

If you using something that don't have those options, only way for you is to replace ENV variables via `REPLACE_OS_VARS=true`. You can read more about it at [Distillery docs](https://hexdocs.pm/distillery/getting-started.html#vm-configuration).
