### ISSUE TITLE
`get_env/2` inconsistent with `Application` for type range

### ISSUE THREAD

**Issue by sjl2** [Nebo15/confex#26]
It seems that `Confex.get_env` errors when the config value is set to a range. 

### Replicate
1. Configure a variable to be of type range.
```elixir
config :test_app,
  range: 1..5,
  ...
```
2. Open app with `iex`.
```sh
$ iex -S mix
```
3. See `Application` behavior (desired).
```sh
iex(1)> Application.get_env(:jessie, :range)
1..5
```
4. See `Confex` behavior.
```sh
iex(4)> Confex.get_env(:jessie, :range)
** (FunctionClauseError) no function clause matching in Confex.Resolver.reduce_map/2

    The following arguments were given to Confex.Resolver.reduce_map/2:

        # 1
        1

        # 2
        %{}

    Attempted function clauses (showing 4 out of 4):

        defp reduce_map({key, nil}, acc)
        defp reduce_map({key, list}, acc) when is_list(list)
        defp reduce_map({key, map}, acc) when is_map(map)
        defp reduce_map({key, value}, acc)

    (confex) lib/confex/resolver.ex:61: Confex.Resolver.reduce_map/2
    (elixir) lib/range.ex:93: Enumerable.Range.reduce/5
    (elixir) lib/enum.ex:1872: Enum.reduce_while/3
    (confex) lib/confex/resolver.ex:41: Confex.Resolver.resolve/1
    (confex) lib/confex.ex:199: Confex.get_env/3
```

### Error

It seems that the error here stems from the range type not being equivalent to a list. Because of this, it doesn't match any of the function headers because `is_list(1..n)` returns `false`.

### Usage Patch 
For those blocked by this, a patch we've found that converting the range to a list (which is supported) with [`Enum.to_list/1`](https://hexdocs.pm/elixir/Enum.html#to_list/1) is a simple enough fix that allows us to avoid mixing `Confex` and `Application` usage. We don't have a many ranges in our configs, but if we did, this patch would be less than ideal. 

**Example**
```
# replace this: 
config :test_app, range: 1..5 # errors

# with this:
config :test_app, range: Enum.to_list(1..5)
```

**Comment by AndrewDryga** [comment]
That's a good catch @sjl2. It's fixed on master, going to fix other Elixir types that stored in map and push to hex.
