### ISSUE TITLE
Lists of lists of config

### ISSUE THREAD

**Issue by bernardd** [Nebo15/confex#32]
Hey there,
I have a case where want to resolve system variables in a nested list (specifically it's config for Redlock - see the example at https://github.com/lyokato/redlock#single-node-mode).

The simplest example is something like:
```
config :my_app,
  servers: [
    [
      host: {:system, :string, "SERVER_HOST"},
      port: {:system, :integer, "SERVER_PORT"}
    ]
  ]
```

Looking at the test at `resolver_test:90`, you evidently don't want list elements to resolve under certain situations (I'm not 100% clear on why, but I'm sure there's a good reason), and this case seems to fall under that non-resolving class. I'd suggest, though, that the case above seems like a pretty reasonable one to have resolving (or, otherwise, I'd love to hear if there's an alternative way to go about it).

Cheers

**Comment by AndrewDryga** [comment]
Hey @bernardd, I'd be happy to accept PR that allows us to resolve configuration for your case 👍. TBH I don't remember why that test exists too.

**Comment by bernardd** [comment]
Sweet. I'll have a stab at that tomorrow.
