### ISSUE TITLE
Question on differences from Application.get_env

### ISSUE THREAD

**Issue by techgaun** [Nebo15/confex#41]
I wanted to bring up this detail that differs from `Application.get_env`. Let me just jump into the example I have here:
My config block: https://github.com/techgaun/confex-sample/blob/86a50a2a81d226235987fa7d579891c2bab27e18/config/config.exs#L32-L36

My test block: https://github.com/techgaun/confex-sample/blob/86a50a2a81d226235987fa7d579891c2bab27e18/test/confex_sample_test.exs#L5-L10

The assertion fails as:

```
1) test Application.get_env & Confex.get_env difference (ConfexSampleTest)
     test/confex_sample_test.exs:5
     Assertion with === failed
     code:  assert app_conf === confex_conf
     left:  [list: [name: {:system, "CONFEX_MY_NAME"}, address: "Earth"]]
     right: nil
     stacktrace:
       test/confex_sample_test.exs:9: (test)
```

As you can see, if any of the parameters is not resolved there, the `nil` is returned instead for the entire `list`. Its probably by design but at least as an opt-in, it would be nice to get either of the following:

```elixir
# unresolved plain
 [list: [name: {:system, "CONFEX_MY_NAME"}, address: "Earth"]]

# resolved but with :error
 [list: [name: :error, address: "Earth"]]
```

**Comment by AndrewDryga** [comment]
@techgaun both links point to the same place, but I think you can get `:error` when environment variable is not set by adding a third element (default value), like so: `{:system, "CONFEX_MY_NAME", :error}`.

**Comment by techgaun** [comment]
@AndrewDryga thanks for the response. Updated the link.

I have since posting this issue used the tuples like you mentioned above which works fine. I am in really dilemma regarding this here. On one thought, I think being explicity about giving the default value as the last element is a reasonable decision and its actually explicit as well. On the other thought, if we were to use Application.get_env, we would probably try to achieve the same thing of fetching from env by doing:
```elixir
config :confex_sample, :example,
  list: [
    name: System.get_env("CONFEX_MY_NAME"),
    address: "Earth"
  ]
```

And, if the envvar is not set, the `Application.get_env` would result in:
```elixir
Application.get_env(:confex_sample, :example)
> [list: [name: nil, address: "Earth"]]
```
I would expect the similar result from Confex as well instead of `nil` for entire block. Even though we are using two different syntaxes, my intention would be same for both and thus I would expect same result.

Regardless, I am going to close this issue because the default value syntax works fine. Thanks for your input. Closing the issue.

**Comment by AndrewDryga** [comment]
I agree that in some cases you would like to get `nil` there. Initial motivation was that Confex is used to configure application in production and we don't really want a production app to start when configuration is missing for some reason (which is much harder to debug).
