### ISSUE TITLE
More flexible adapter interface

### ISSUE THREAD

**Issue by bernardd** [Nebo15/confex#51]
Hi there! I was just looking at implementing an adapter for AWS Secrets Manager, and hit an issue (that I'd already encountered when writing my Vault one but decided to just ignore). The current adapter interface is a simple `String.t() -> String.t()` mapping, which is fine for environment variables but both vault and SM have names for both the secret and the values therein. So to fully describe the "key" for a value being pulled from them you need both the secret name and the key within the secret.  I can think of a few ways of approaching this:

* Do what I did in `ConfexVault` and just force the user to always use the key `value` or similar within the secret. In this instance you can still declare the value as `{{:via, MyAdapter}, "some_name"}`, but you're restricted in how you use the store itself.
* Squish the secret name and key together and let the adapter prise them apart, meaning you had something like `{{:via, MyAdapter}, "secret_name/secret_key"}`.
* Extend the adapter behaviour so that it can take a more flexible input term, say `tuple(String.t()) | String.t() -> String.t()`. Then you could do something like `{{:via, MyAdapter}, {"secret_name", "secret_key"}}`

The first two feel kind of half-baked, but the third would obviously require some changes to Confex itself, even if only to the behaviour's typespec.

I'd be really interested in getting your thoughts on the best way to approach this.

**Comment by bernardd** [comment]
Actually on reflection a Keyword list would probably be more appropriate for the last option, eg: {{:via, MyAdapter}, name: "secret_name", key: "secret_key"}

**Comment by AndrewDryga** [comment]
Hey @bernardd, I think it's a good idea for an adapter to accept just `term()`. This way we won't have people hitting the same limitations when they need not a keyword or string, but something else. It should not break anything as I remember.

**Comment by bernardd** [comment]
Closed by #52
